const fs = require('fs').promises; // Import the fs module

const axios = require('axios');

const getJapaneseWords = async words => {
  try {
    const dataToWrite = []; // Array to store extracted data

    for (const word of words) {
      const response = await axios.post('http://localhost:11434/api/generate', {
        model: 'llama3.1:8b',
        stream: false,
        prompt: `give me the kanji for the word ${word}? {hiragana: ""} only return object, nothing else`
      });

      console.log(`Ollama Local Response for ${word}:`, response.data.response);
      // Add the extracted data to the array
      dataToWrite.push(response.data.response);
    }

    // Write data to a JSON file
    await fs.writeFile(
      'llama13_nouns.json',
      JSON.stringify(dataToWrite, null, 2)
    );
    console.log('Data written to json successfully.');
  } catch (error) {
    console.error('Error making local API request to Ollama:', error.message);
  }
};

// Placeholder array for kanjis (replace this with your actual kanji array)
const wordsArray = [
  'lake',
  'cloud',
  'weather'
  // 'day',
  // 'year',
  // 'month',
  // 'week',
  // 'hour',
  // 'minute',
  // 'second',
  // 'chair',
  // 'desk',
  // 'bed',
  // 'table',
  // 'computer',
  // 'phone',
  // 'internet',
  // 'game',
  // 'sport',
  // 'music',
  // 'picture',
  // 'camera',
  // 'photo',
  // 'bookshelf',
  // 'shelf',
  // 'box',
  // 'container',
  // 'bottle',
  // 'plate',
  // 'bowl',
  // 'spoon',
  // 'knife',
  // 'coffee',
  // 'tea',
  // 'milk',
  // 'bread',
  // 'fruit',
  // 'vegetable',
  // 'garden',
  // 'park',
  // 'street',
  // 'building',
  // 'room',
  // 'door',
  // 'window',
  // 'bed',
  // 'pillow',
  // 'blanket',
  // 'carpet',
  // 'sofa',
  // 'chair',
  // 'glass',
  // 'cup',
  // 'fork',
  // 'paper',
  // 'pen',
  // 'pencil',
  // 'eraser',
  // 'ruler',
  // 'glue',
  // 'tape',
  // 'scissors',
  // 'magazine',
  // 'newspaper',
  // 'tV',
  // 'radio',
  // 'computer',
  // 'phone',
  // 'camera',
  // 'flashlight',
  // 'battery',
  // 'charger',
  // 'clock',
  // 'calendar',
  // 'diary',
  // 'journal',
  // 'penpal',
  // 'friend',
  // 'family',
  // 'parent',
  // 'child',
  // 'brother',
  // 'sister',
  // 'cousin',
  // 'uncle',
  // 'aunt',
  // 'nephew',
  // 'niece',
  // 'grandparent',
  // 'grandchild',
  // 'neighbor',
  // 'colleague',
  // 'tree',
  // 'flower',
  // 'garden',
  // 'park',
  // 'street',
  // 'building',
  // 'room',
  // 'door',
  // 'window',
  // 'bed',
  // 'pillow',
  // 'blanket',
  // 'carpet',
  // 'sofa',
  // 'chair',
  // 'tablecloth',
  // 'plate',
  // 'glass',
  // 'cup',
  // 'spoon',
  // 'fork',
  // 'knife',
  // 'cloud',
  // 'weather',
  // 'storm',
  // 'rain',
  // 'sunshine',
  // 'moonlight',
  // 'starlight',
  // 'mountain',
  // 'river',
  // 'lake',
  // 'ocean',
  // 'sea',
  // 'shore',
  // 'beach',
  // 'island',
  // 'compass',
  // 'map',
  // 'guidebook',
  // 'tourist',
  // 'traveler',
  // 'passport',
  // 'visa',
  // 'plane',
  // 'train',
  // 'car',
  // 'bus',
  // 'taxi',
  // 'hotel',
  // 'restaurant',
  // 'cafe',
  // 'shop',
  // 'market',
  // 'store',
  // 'warehouse',
  // 'office',
  // 'chair',
  // 'table',
  // 'bed',
  // 'desk',
  // 'computer',
  // 'phone',
  // 'camera',
  // 'book',
  // 'magazine',
  // 'newspaper',
  // 'pen',
  // 'pencil',
  // 'eraser',
  // 'paper',
  // 'file',
  // 'folder',
  // 'shelf',
  // 'drawer',
  // 'closet',
  // 'mirror',
  // 'window',
  // 'door',
  // 'ceiling',
  // 'wall',
  // 'floor',
  // 'carpet',
  // 'rug',
  // 'pillow',
  // 'mattress',
  // 'blinds',
  // 'fan',
  // 'air',
  // 'conditioner',
  // 'heater',
  // 'lamp',
  // 'light',
  // 'bulb',
  // 'switch',
  // 'plug',
  // 'socket',
  // 'cord',
  // 'wire',
  // 'battery',
  // 'charger',
  // 'adapter',
  // 'power',
  // 'source',
  // 'generator',
  // 'motor',
  // 'engine',
  // 'gearbox',
  // 'transmission',
  // 'axle'
];

// Make the API requests for each kanji
getJapaneseWords(wordsArray);
